### ISSUE TITLE
Adapter la taille des bubbles en fonction du nombre de mails

### ISSUE THREAD

**Issue by ChloeMoser** [SocialGouv/archimail#80]
### EPIC

https://github.com/SocialGouv/archifiltre-private/issues/3

### AFTER

https://github.com/SocialGouv/archimail/issues/29

### Contexte

Quand on dépose un pst, on affche sous forme de Bubbles l'ensemble des mails par domaine puis par correspondant puis par année puis l'ensemble des mails concerné.

### Définition du(des) problème(s)

L'affichage actuel ne rend pas compte de l'importance (en volume de mails) de chaque élément affiché.

### Solution

ETQ utilisateur d'Archifiltre-Mails
JVP visualiser par catégorie (domaine, correspondants, années) le nombre de mails concerné
AD pouvoir comprendre visuellement l'importance de chaque élément. 

### Les tests e2e doivent-ils passer ?

- [ ] e2e

### Valeur Business

BV:XL

**Comment by lsagetlethias** [comment]
Duplicate of #29
